### ISSUE TITLE
Invalid argument supplied for foreach

### ISSUE THREAD

**Issue by elpulga** [Potelo/laravel-block-bots#14]
I'm getting the following error

`In Configuration.php line 9:
  Invalid argument supplied for foreach()`

What am I missing?

**Comment by jprodrigues70** [comment]
Hi @elpulga 

This error occurs when you don't have a file called `block-bots.php` in your `config` folder. Check if you have permissions issues.

Try to run
```
php artisan vendor:publish --provider="Potelo\LaravelBlockBots\BlockBotsServiceProvider"
```
And Laravel will copy the file from vendor to the config folder.

**Comment by elpulga** [comment]
I get the same error when running that command
I manually added the file to my config folder but I still have the same problem.

**Comment by jprodrigues70** [comment]
What's your Laravel version? 

I can't reproduce your problem. I think it seems to be a issue on your project.

Try:
```
php artisan config:clear
```

And
```
composer dump-autoload
```

And try again.

**Comment by jprodrigues70** [comment]
Closed, because it's not a problem with laravel-block-bots.
