### ISSUE TITLE
Laravel 9 compatible

### ISSUE THREAD

**Issue by MatejMozola** [Potelo/laravel-block-bots#18]
Hello, I am using Laravel 9 so composer wont allow me to install the package. Could u please update the package to be compatible with Laravel 9? Thank you so much and keep up the good work. <3

**Comment by gabrielpeixoto** [comment]
Hello @MatejMozola 

We added support. Could you test and confirm if it worked?

**Comment by MatejMozola** [comment]
yeah installed the package successfully thanks 💯
