### ISSUE TITLE
Support Laravel 10 compatible

### ISSUE THREAD

**Issue by dungnh** [Potelo/laravel-block-bots#19]
Could you please update the package to be compatible with Laravel 10?

**Comment by colivinggit** [comment]
Please update this package for Laravel 10

**Comment by amoktar** [comment]
Yes please

**Comment by gabrielpeixoto** [comment]
Done. Just update to version 1.6.0 of the package. 😄

**Comment by amoktar** [comment]
Thanks @gabrielpeixoto

**Comment by amoktar** [comment]
sorry @gabrielpeixoto but I get composer error about predis/predis
`
Problem 1
    - Root composer.json requires potelo/laravel-block-bots ^1.6 -> satisfiable by potelo/laravel-block-bots[1.6.0].
    - potelo/laravel-block-bots 1.6.0 requires predis/predis ^1.1 -> found predis/predis[v1.1.0, ..., v1.1.10] but it conflicts with your root composer.json require (^2.2).
`

**Comment by gabrielpeixoto** [comment]
@AMoktar 

I will look as soon as possible. If you want, you can make a PR and send it, which would speed things up.

**Comment by gabrielpeixoto** [comment]
@AMoktar Could you test with version 1.6.1?

**Comment by amoktar** [comment]
@gabrielpeixoto it is working fine "laravel/framework": "^10.10"

Thanks a lot
